# This is a basic workflow to help you get started with Actions

name: Python CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: autopep8
      id  : autopep8
      uses: peter-evans/autopep8@v1
      with:
        args: --recursive --in-place --aggressive --aggressive .

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: autopep8 action fixes
        committer: Peter Evans <peter-evans@users.noreply.github.com>
        title: Fixes by autopep8 action
        body: This is an auto-generated PR with fixes by autopep8.
        labels: autopep8, automated pr
        reviewers: peter-evans
        branch: autopep8-patches